<?php
/**	op-unit-database-tutorial:/SQLite.phtml
 *
 * @created    2025-12-08
 * @license    Apache-2.0
 * @package    op-unit-database
 * @subpackage tutorial
 * @copyright  (C) 2025 Tomoaki Nagahara
 */

/**	Declare strict type
 *
 */
declare(strict_types=1);

/**	Namespace
 *
 */
namespace OP;

?>
<section class="markdown" data-translation="true">
# How to connect to SQLite

```php
OP()->Unit()->Database()->Connect('sqlite:/var/private/db.sqlite3');
```
</section>

<section class="markdown" data-translation="true">
# Feedback
<?php OP()->Template('tutorial:/feedback.phtml') ?>
</section>
